### ISSUE TITLE
Boolean field doesn't reflect falsy state

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/components#2]
True is saved as `"1"`, False as `"0"`.

In javascript, both of these expressions evaluate to true.

If you open the settings while the value is `"0"`, the switch will be shown as enabled. It should be shown as disabled in this case.

Here's how this case is handled in another extension https://github.com/clarkwinkelmann/catch-the-fish/blob/59b09b2f946783096a571f982d51bc789cedc5c4/js/src/admin/modals/CTFSettingsModal.js#L55

**Comment by datitisev** [comment]
Yeah, I saw this occurring, didn't have the time to fix it though. It should be cast to `Number`. I'll fix this now.

**Comment by clarkwinkelmann** [comment]
Perfect! I'm using it in User Directory for a new setting
